

services:
  embedding_server:
    build:
      context: ./Microservice1
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./Microservice1:/app
    networks:
      - plagiarism-net

  plagiarism_check_api:
    build:
      context: ./Microservice2
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Microservice2:/app
    depends_on:
      - embedding_server  # Ensure embedding server starts before plagiarism API
    networks:
      - plagiarism-net

# Create a custom network for the services to communicate
networks:
  plagiarism-net:
    driver: bridge
